# Permalinks
permalink:      /:title

# Setup
title:          Z00MER's
paginate:       10
baseurl:        ""
url:            "https://hazemsamir.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Hazem Ashmawy
  url:          http://hazemsamir.github.io
  email:        hazem.s.ashmawy@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
